In [144]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

# Connect to Website 
URL = 'https://api.stocktwits.com/widgets/stream?width=300&amp;height=1700&amp;domain=finviz.com&amp;scrollbars=0&amp;streaming=true&amp;header=0&amp;limit=24&amp;symbol=DB&amp;border_color=22262F&amp;border_color_2=22262F&amp;box_color=22262F&amp;header_text_color=C3C6D0&amp;divider_color=353945&amp;stream_color=22262F&amp;username_color=F3F3F5&amp;username_hover_color=F3F3F5&amp;username_font=Verdana%2C%20Arial%2C%20Tahoma&amp;username_size=12&amp;divider_type=solid&amp;link_color=57aefb&amp;link_hover_color=57aefb&amp;font=Verdana%2C%20Arial%2C%20Tahoma&amp;font_size=12&amp;text_color=C3C6D0&amp;time_color=868EA5&amp;time_font_size=10'

headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 OPR/100.0.0.0","Accept-Encoding": "gzip, deflate, br","Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7","DNT":"1","Connection":"close","Upgrade-Insecure-Requests":"1"}

# Pulling in the content
page = requests.get(URL, headers=headers)

soup = BeautifulSoup(page.content, "html.parser")

columns = soup.find_all(['span','a'], class_=['time','body','username'])

In [145]:
values_table = [column.text.strip() for column in columns]
print(values_table)

['shortvolumes', 'Aug. 6 at 4:41 AM', 'Short sale volume (not short interest) for $DB on 2023-08-04 is 57%. http://shortvolumes.com/?t=DB via @shortvolumes', 'STCKPRO', 'Aug. 5 at 6:00 AM', '$DB NEW ARTICLE : Deutsche Bank Downgrades Moderna (MRNA) https://www.stck.pro/news/DB/58122528/', 'TickerDD_com', 'Aug. 4 at 4:04 PM', 'From 7/3/2023, looking back across 22 Month-Ends for DB, Percentage Change of Average Monthly Price had More Positives (59%)  while Percentage Change of Average Monthly Volume had More Positives (91%)  $DB #DB #DBStock #TickerDD #DBPrice https://www.youtube.com/watch?v=-2146826273', 'WallStreetBuyDip', 'Aug. 4 at 11:32 AM', '$DB never recovered since 2018', 'WallStreetBuyDip', 'Aug. 4 at 11:26 AM', '$DB wild', 'STCKPRO', 'Aug. 4 at 9:50 AM', '$DB NEW ARTICLE : Deutsche Bank AG (DB) Receives a Buy from Warburg Research https://www.stck.pro/news/DB/58057878/', 'STCKPRO', 'Aug. 4 at 8:33 AM', '$DB NEW ARTICLE : Zalando distancing from ‚Äúpeak negativity‚Äù ‚Äì Deutsche Bank https://www.stck.pro/news/DB/58053575/', 'NewAge69', 'Aug. 4 at 5:13 AM', '$DB break the 11 today üíµüòÇüíµ', 'STCKPRO', 'Aug. 4 at 3:27 AM', '$DB NEW ARTICLE : Deutsche Bank Downgrades Qualcomm https://www.stck.pro/news/DB/58039024/', 'shortvolumes', 'Aug. 4 at 1:05 AM', 'Short sale volume (not short interest) for $DB at 2023-08-03 is 54%. http://shortvolumes.com/?t=DB via @shortvolumes', 'NewAge69', 'Aug. 3 at 6:22 AM', '$DB 9s..in ‚Ç¨ not in $', 'Contrarian_Dan', 'Aug. 2 at 4:59 PM', "$DB I'm buyer in the 9's.  \n \nPretty soon gross profit will equal 40% of the entire market cap of this bank.", 'risenhoover', 'Aug. 2 at 12:58 PM', '$DB DB / Deutsche Bank AG - Registered Shares Price Target Updated \nhttps://fintel.io/sfo/us/db?utm_source=stocktwits.com&utm_medium=referral&utm_campaign=pricetarget', 'Contrarian_Dan', 'Aug. 2 at 12:26 PM', '$DB Stupid cheap.', 'tickeron', 'Aug. 2 at 11:24 AM', '$CM vs. $DB vs. $GDL: what is the best stock to add to your portfolio? #CanadianImperialBankofCommerce https://srnk.us/go/4815433', 'HarveyToronto', 'Aug. 1 at 2:43 PM', '@NewAge69 not bad they are going to buy back 45 million shares $DB', 'MarketBeat', 'Aug. 1 at 2:36 PM', "DBV Technologies's market outperform rating reiterated at JMP Securities. $4.00 PT. www.marketbeat.com/stocks/NASDAQ/DBVT/price-target/ $DB", 'NewAge69', 'Aug. 1 at 1:12 PM', '$DB arp\nStarts tomorrow\nhttps://www.finanznachrichten.de/nachrichten-2023-08/59726916-eqs-cms-deutsche-bank-ag-veroeffentlichung-einer-kapitalmarktinformation-022.htm', 'LizardPeopleStock', 'Jul. 30 at 11:56 PM', '$RYCEY https://www.marketscreener.com/quote/stock/ROLLS-ROYCE-HOLDINGS-PLC-4004084/news/Deutsche-Bank-Boosts-Rolls-Royce-PT-Affirms-Buy-Rating-44437984/\n\n$DB $TOPG', 'macroaxis', 'Jul. 30 at 8:09 AM', '$ESSA - Should I keep both ESSA Bancorp and Deutsche Bank ( $DB ) in the same portfolio? Next fiscal quarter end is on 30th of September 2023 https://www.macroaxis.com/invest/pair-correlation/ESSA/DB/ESSA-vs-Deutsche #portfolio_prospective #better_portfolio #diversify', 'Atlas44', 'Jul. 29 at 11:12 AM', '$DB I think this is why the stock dropped late day Wednesday and Thursday. https://www.reuters.com/business/finance/ecb-mulled-raising-banks-mandatory-reserves-inflation-fight-sources-2023-07-27/  \n \nhttps://www.bloomberg.com/news/articles/2023-07-28/deutsche-bank-cfo-blasts-ecb-for-scrapping-interest-on-reserves#xj4y7vzkg', 'shortvolumes', 'Jul. 29 at 12:50 AM', 'Short sale volume (not short interest) for $DB on 2023-07-28 is 43%. http://shortvolumes.com/?t=DB via @shortvolumes', 'danlo', 'Jul. 28 at 6:07 PM', '$DWAC many people are saying Trump diverted Covid Funds through a raggedy internet bank, Axos, to give himself a lifeline for loans he had coming due. Some say it was a lender of last resort because conventional banks would not do business with a terrorist, even $DB.', 'Quantisnow', 'Jul. 28 at 2:18 PM', '$DB üìú SEC Form 6-K/A filed by Deutsche Bank AG (Amendment)\n\nhttps://quantisnow.com/i/4810958?utm_source=stocktwits\n\n45 seconds delayed.', 'shortvolumes', 'Jul. 28 at 2:14 PM', 'Short sale volume (not short interest) for $DB on 2023-07-27 is 44%. http://shortvolumes.com/?t=DB via @shortvolumes']

In [146]:
columns_table = ['username','time','body']
df = pd.DataFrame(columns = columns_table)

df

Empty DataFrame
Columns: [username, time, body]
Index: []

In [147]:
start = 0 
end = len(values_table)
step = 3
for i in range(start, end, step):
    x = i
    individual_row_data = values_table[x:x+step]
    #print(individual_row_data)
    
    length = len(df)
    df.loc[length] = individual_row_data

In [148]:
#Adding year to df
df["time"] = "2023 " + df["time"]

#Converting Object Date into Pandas DateFrame format
df["time"] = pd.to_datetime(df["time"], format="%Y %b. %d at %I:%M %p")

In [149]:
df

,username,time,body
0,shortvolumes,2023-08-06 04:41:00,Short sale volume (not short interest) for $DB...
1,STCKPRO,2023-08-05 06:00:00,$DB NEW ARTICLE : Deutsche Bank Downgrades Mod...
2,TickerDD_com,2023-08-04 16:04:00,"From 7/3/2023, looking back across 22 Month-En..."
3,WallStreetBuyDip,2023-08-04 11:32:00,$DB never recovered since 2018
4,WallStreetBuyDip,2023-08-04 11:26:00,$DB wild
5,STCKPRO,2023-08-04 09:50:00,$DB NEW ARTICLE : Deutsche Bank AG (DB) Receiv...
6,STCKPRO,2023-08-04 08:33:00,$DB NEW ARTICLE : Zalando distancing from ‚Äúpea...
7,NewAge69,2023-08-04 05:13:00,$DB break the 11 today üíµüòÇüíµ
8,STCKPRO,2023-08-04 03:27:00,$DB NEW ARTICLE : Deutsche Bank Downgrades Qua...
9,shortvolumes,2023-08-04 01:05:00,Short sale volume (not short interest) for $DB...
10,NewAge69,2023-08-03 06:22:00,$DB 9s..in ‚Ç¨ not in $
11,Contrarian_Dan,2023-08-02 16:59:00,$DB I'm buyer in the 9's. \n \nPretty soon gr...
12,risenhoover,2023-08-02 12:58:00,$DB DB / Deutsche Bank AG - Registered Shares ...
13,Contrarian_Dan,2023-08-02 12:26:00,$DB Stupid cheap.
14,tickeron,2023-08-02 11:24:00,$CM vs. $DB vs. $GDL: what is the best stock t...
15,HarveyToronto,2023-08-01 14:43:00,@NewAge69 not bad they are going to buy back 4...
16,MarketBeat,2023-08-01 14:36:00,DBV Technologies's market outperform rating re...
17,NewAge69,2023-08-01 13:12:00,$DB arp\nStarts tomorrow\nhttps://www.finanzna...
18,LizardPeopleStock,2023-07-30 23:56:00,$RYCEY https://www.marketscreener.com/quote/st...
19,macroaxis,2023-07-30 08:09:00,$ESSA - Should I keep both ESSA Bancorp and De...
20,Atlas44,2023-07-29 11:12:00,$DB I think this is why the stock dropped late...
21,shortvolumes,2023-07-29 00:50:00,Short sale volume (not short interest) for $DB...
22,danlo,2023-07-28 18:07:00,$DWAC many people are saying Trump diverted Co...
23,Quantisnow,2023-07-28 14:18:00,$DB üìú SEC Form 6-K/A filed by Deutsche Bank AG...
24,shortvolumes,2023-07-28 14:14:00,Short sale volume (not short interest) for $DB...

In [150]:
#time_stamp = datetime.datetime.now()
#today = time_stamp.strftime("%Y-%m-%d")
today = pd.Timestamp.today().date()
print(today)

2023-08-06

In [151]:
today_data = (df['time'].dt.date == today)
df_today = df[today_data]

df_today

,username,time,body
0,shortvolumes,2023-08-06 04:41:00,Short sale volume (not short interest) for $DB...

In [153]:
#initial insertion of the data into the csv (only run this one time - otherwise data will get deleted)
#with open('Fiviz_Tweet_Output.csv', 'w', newline='', encoding='UTF8') as f:
#    writer = csv.writer(f)
#    writer.writerow(df_today)
#    for row in range(df_today.shape[0]):
#        writer.writerow(df_today.iloc[row].tolist())

In [157]:
df_today_ = pd.read_csv(r'C:\Users\Elvan\Documents\Fiviz_Tweet_Output.csv')

df_today_

,username,time,body
0,shortvolumes,2023-08-06 04:41:00,Short sale volume (not short interest) for $DB...

In [ ]:
#appending data into the csv
#with open('Fiviz_Tweet_Output.csv', 'a+', newline='', encoding='UTF8') as f:
#    writer = csv.writer(f)
#    for row in range(df_today.shape[0]):
#        writer.writerow(df_today.iloc[row].tolist())